# Pengaturan API Telegram
telegram:
  api_id: ${API_ID}
  api_hash: ${API_HASH}
  phone_number: ${PHONE_NUMBER}

# Pengaturan Notifikasi
notification:
  personal_chat_id: ${PERSONAL_CHAT_ID}

# Pengaturan File dan Direktori
directories:
  data: "data"
  logs: "logs"

files:
  groups: "groups.txt"
  blacklist: "blacklist.txt"
  log: "bot.log"
  error_log: "bot.log.error"
  slow_mode: "slow_mode_info.json"
  messages:
    - "pesan1.txt"
    - "pesan2.txt"
    - "pesan3.txt"
    - "pesan4.txt"
    - "pesan5.txt"

# Pengaturan Logging
logging:
  level: "INFO"

# Pengaturan Pengiriman Pesan
message_sending:
  min_delay: 7
  max_delay: 12
  default_max_length: 4096

# Pengaturan Penjadwalan
scheduling:
  min_interval: 1.2
  max_interval: 1.5

# Pengaturan Penanganan Kesalahan
error_handling:
  max_retries: 3
  retry_delay: 60

# Pengaturan Cache
cache:
  expiry: 3600

# Pengaturan Debug
debug:
  enabled: true
