# Pengaturan API Telegram
telegram:
  api_id: ${API_ID}
  api_hash: ${API_HASH}
  phone_number: ${PHONE_NUMBER}

# Pengaturan Notifikasi
notification:
  personal_chat_id: ${PERSONAL_CHAT_ID}

# Pengaturan File dan Direktori
directories:
  data: "./data"
  logs: "./logs"

files:
  messages:
    - "pesan1.txt"
    - "pesan2.txt"
    - "pesan3.txt"
    - "pesan4.txt"
    - "pesan5.txt"
  groups: "groups.txt"
  blacklist: "blacklist.txt"
  slow_mode_info: "slow_mode_info.json"

# Pengaturan Logging
logging:
  level: "INFO"

# Pengaturan Pengiriman Pesan
message_sending:
  min_intra_batch_delay: 1.0
  max_intra_batch_delay: 3.0
  batch_size: 4
  min_inter_batch_delay: 20
  max_inter_batch_delay: 30
  default_max_length: 4096

# Pengaturan Penjadwalan
scheduling:
  min_interval: 1.3
  max_interval: 1.5

# Pengaturan Penanganan Kesalahan
error_handling:
  max_retries: 3
  retry_delay: 60

# Pengaturan Cache
cache:
  expiry: 3600

# Pengaturan Umum
general:
  timezone: "UTC"

# Pengaturan Debug
debug:
  enabled: true
  profiling: true
