[tool.ruff]
# Mengatur versi Python target
target-version = "py38"

# Mengatur panjang baris maksimum sesuai dengan Black
line-length = 88

# Mengaktifkan semua aturan yang relevan dengan proyek ini
select = [
    "E",   # Kesalahan pycodestyle
    "W",   # Peringatan pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "C",   # flake8-comprehensions
    "B",   # flake8-bugbear
    "S",   # flake8-bandit (keamanan)
    "ANN", # flake8-annotations
    "N",   # pep8-naming
    "D",   # pydocstyle
    "UP",  # pyupgrade
    "RUF", # Aturan khusus Ruff
    "PT",  # flake8-pytest-style
    "SIM", # flake8-simplify
    "TCH", # flake8-type-checking
    "ARG", # flake8-unused-arguments
    "ERA", # eradicate
]

# Mengabaikan beberapa aturan yang mungkin terlalu ketat untuk proyek ini
ignore = [
    "D203",  # 1 baris kosong diperlukan sebelum docstring kelas
    "D212",  # Ringkasan docstring multi-baris harus dimulai pada baris pertama
    "ANN101",  # Anotasi tipe yang hilang untuk self dalam metode
    "ANN102",  # Anotasi tipe yang hilang untuk cls dalam classmethod
]

# Mengabaikan beberapa aturan untuk file tertentu
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]  # Mengizinkan impor yang tidak digunakan di __init__.py
"tests/*" = ["S101"]  # Mengizinkan penggunaan assert dalam tes

# Konfigurasi untuk pydocstyle
[tool.ruff.pydocstyle]
convention = "google"

# Konfigurasi untuk flake8-annotations
[tool.ruff.flake8-annotations]
allow-star-arg-any = true

# Konfigurasi untuk isort
[tool.ruff.isort]
known-third-party = ["telethon", "pydantic", "asyncio"]

# Konfigurasi untuk formatter Ruff
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

# Konfigurasi untuk flake8-bugbear
[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["pydantic.Field"]

# Konfigurasi untuk pyupgrade
[tool.ruff.pyupgrade]
# Menggunakan sintaks walrus operator (Python 3.8+)
keep-runtime-typing = true

# Konfigurasi untuk flake8-bandit (keamanan)
[tool.ruff.flake8-bandit]
hardcoded-tmp-directory = ["tmp", "temp"]
