[tool.ruff]
# Mengatur versi Python target
target-version = "py38"

# Mengatur panjang baris maksimum sesuai dengan Black
line-length = 88

# Mengaktifkan semua aturan yang relevan dengan proyek Anda
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "C",   # flake8-comprehensions
    "B",   # flake8-bugbear
    "S",   # flake8-bandit (security)
    "ANN", # flake8-annotations
    "N",   # pep8-naming
    "D",   # pydocstyle
    "UP",  # pyupgrade
    "RUF", # Ruff-specific rules
    "PT",  # flake8-pytest-style
    "SIM", # flake8-simplify
    "TCH", # flake8-type-checking
    "ARG", # flake8-unused-arguments
    "ERA", # eradicate
]

# Mengabaikan beberapa aturan yang mungkin terlalu ketat untuk proyek Anda
ignore = [
    "D203",  # 1 blank line required before class docstring
    "D212",  # Multi-line docstring summary should start at the first line
    "ANN101",  # Missing type annotation for self in method
    "ANN102",  # Missing type annotation for cls in classmethod
]

# Mengabaikan beberapa aturan untuk file tertentu
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]  # Unused imports in __init__.py
"tests/*" = ["S101"]  # Allow assert in tests

# Konfigurasi untuk pydocstyle
[tool.ruff.pydocstyle]
convention = "google"

# Konfigurasi untuk flake8-annotations
[tool.ruff.flake8-annotations]
allow-star-arg-any = true

# Konfigurasi untuk isort
[tool.ruff.isort]
known-third-party = ["telethon", "pydantic", "asyncio"]

# Konfigurasi untuk formatter Ruff
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

# Konfigurasi untuk flake8-bugbear
[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["pydantic.Field"]

# Konfigurasi untuk pyupgrade
[tool.ruff.pyupgrade]
# Gunakan sintaks walrus operator (Python 3.8+)
keep-runtime-typing = true

# Konfigurasi untuk flake8-bandit (keamanan)
[tool.ruff.flake8-bandit]
hardcoded-tmp-directory = ["tmp", "temp"]
