[tool.ruff]
fix = true
line-length = 88
target-version = "py38"
exclude = ["tests/*", "docs/*", "examples/*"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["COM812", "ISC001"]
unfixable = []
per-file-ignores = {"__init__.py" = ["E402", "F401"]}
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true

[tool.pyright]
typeCheckingMode = "basic"
